# Generated by Django 4.1.7 on 2023-03-28 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=200)),
                ('Manufacturer', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField()),
                ('Expiry_Date', models.DateField(default=False)),
                ('Date_Issued', models.DateTimeField(verbose_name='date issued')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Date_Issued'],
            },
        ),
    ]
